server:
    port: 8080

security:
  user:
    password: none
#  oauth2:
#    client:
#      clientId: gateway
#      clientSecret: 123456
#      accessTokenUri: http://localhost:8081/uaa/oauth/token
#      userAuthorizationUri: http://localhost:8081/uaa/oauth/authorize
#    resource:
#      userInfoUri: http://localhost:8081/uaa/user
#      prefer-token-info: false

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
#  host:
#    connect-timeout-millis: 20000
#    socket-timeout-millis: 20000
spring:
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: false
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://mysql_server:3306/${MYSQL_DATABASE_NAME}?useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_USER_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
    
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  ribbonIsolationStrategy: THREAD
  sensitive-headers: Cookie,Set-Cookie
  routes:
    oauth:
      path: /uaa/**
      url: http://authentication-server/uaa
      
    register-service:
      path: /register/**
      url: http://register-service/register

    account-service:
      path: /account/**
      url: http://account-service/account

    institution-service:
      path: /institution/**
      url: http://institutions-service/institution

    region-service:
      path: /regions/**
      url: http://institutions-service/regions

    branch-service:
      path: /branches/**
      url: http://institutions-service/branches

    agency-service:
      path: /agency/**
      url: http://institutions-service/agency

    holiday-service:
      path: /holidays/**
      url: http://institutions-service/holidays

    services-details-service:
      path: /services/**
      url: http://institutions-service/services

    apps-service:
      path: /apps/**
      url: http://apps-service/apps

    menu-service:
      path: /menu/**
      url: http://authentication-server/uaa/menu
      
    user-group-service:
      path: /usergroup/**
      url: http://authentication-server/uaa/usergroup

    audit-trail-service:
      path: /auditlogs/**
      url: http://audit-trail-service/auditlogs

    device-service:
      path: /device/**
      url: http://device-service/device

    support-service:
      path: /supports/**
      url: http://support-service/supports

    complaint-service:
      path: /complaints/**
      url: http://complaint-service/customers/complaints

    dictionary-service:
      path: /dictionary/**
      url: http://dictionary-service/dictionary

    iswitch-service:
      path: /iswitch/**
      url: http://iswitch-service/iswitch

    assets-inventory-service:
      path: /inventory/**
      url: http://assets-inventory-service/inventory

    cron-scheduler-service:
      path: /cron/**
      url: http://cron-scheduler-service/cron
      
    supplier-service:
      path: /suppliers/**
      url: http://supplier-service/suppliers

    invoice-service:
      path: /invoice/**
      url: http://invoice-service/invoices

    receipt-service:
      path: /receipt/**
      url: http://receipt-service/receipt

    accounting-service:
      path: /accounting/**
      url: http://accounting-service/accounting

    customer-service:
      path: /customers/**
      url: http://customer-service/customers
      
    teller-service:
      path: /teller/**
      url: http://teller-transactions-service/teller

    teller-rule-service:
      path: /tellerrule/**
      url: http://teller-transactions-service/tellerrule
      
    transaction-service:
      path: /transactions/**
      url: http://teller-transactions-service/transactions

    transaction-rule-service:
      path: /transactionrule/**
      url: http://teller-transactions-service/transactionrule

    transaction-standingorder-service:
      path: /standingorder/**
      url: http://teller-transactions-service/standingorder

    open-branch-service:
      path: /branch/**
      url: http://teller-transactions-service/branch

    transaction-accrual-service:
      path: /accruals/**
      url: http://teller-transactions-service/accruals
        
    products-service:
      path: /products/**
      url: http://products-service/products

    crb-identity-service:
      path: /identity/**
      url: http://crb-identity-service/identity

    crb-score-service:
      path: /score/**
      url: http://crb-identity-service/score

    crb-delinquency-service:
      path: /delinquency/**
      url: http://crb-identity-service/delinquency

    aml-service:
      path: /aml/**
      url: http://aml-service/aml

    till-service:
      path: /till/**
      url: http://teller-transactions-service/till

    till-branch-service:
      path: /branch/till/**
      url: http://teller-transactions-service/branch/till

    dashboard-service:
      path: /dashboard/**
      url: http://dashboard-service/dashboard

    document-management-service:
      path: /document/**
      url: http://document-management-service/document

    customer-account-service:
      path: /customer/account/**
      url: http://customer-account-service/customer/account

    loans-service:
      path: /loans/**
      url: http://loans-service/loans
    
    loans-service-dev:
      path: /loans_v3/**
      url: http://loans-service-dev/loans
      
    loans-settings-service:
      path: /settings/**
      url: http://loans-settings-service/settings
      
    operational-settings-service:
      path: /operational/settings/**
      serviceId: operational-settings-service

    retail-pos-service:
      path: /retail/**
      url: http://retail-pos-service/retail

    sales-service:
      path: /sales/**
      url: http://sales-service/sales

    payment-service:
      path: /payments/**
      url: http://payment-service/payments

    messaging-service:
      path: /message/**
      url: http://messaging-service/message
      
    purchase-order-invoice-service:
      path: /items/product/**
      url: http://purchase-order-invoice-service/items/product
      
    ussd-service:
      path: /ussd/**
      url: http://ussd-service/ussd
      
    transaction-test-service:
      path: /transactions_test/**
      url: http://teller-transactions-test-service/transactions_test
      
    teller-test-service:
      path: /teller_test/**
      url: http://teller-transactions-test-service/teller_test
      
    open-branch-test-service:
      path: /branch_test/**
      url: http://teller-transactions-test-service/branch_test
      
    till-test-service:
      path: /till_test/**
      url: http://teller-transactions-test-service/till_test
